In [1]:
import numpy as np

In [2]:
def df_w(w):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    w1, w2 = w
    dw1 = 0.2 * w1
    dw2 = 4 * w2
    dW = np.array([dw1, dw2])
    ########################################################

    return dW

In [3]:
def sgd_momentum(W, dW, lr, V, beta):
    """
    Thực hiện thuật tóan Gradient Descent + Momentum để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    beta -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    """
    #################### YOUR CODE HERE ####################
    V = beta * V + (1 - beta) * dW
    W = W - lr * V
    ########################################################
    return W, V

In [4]:
def train_p1(optimizer, lr, beta, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, v1, v2
    # append cặp [w1, w2] vào list results
    for epoch in range(epochs):
        dW = df_w(W)
        W, V = optimizer(W, dW, lr, V, beta)
        results.append(W)
    ########################################################
    return results

In [5]:
train_p1(sgd_momentum, lr=0.6, beta=0.5, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7      ,  0.4000001], dtype=float32),
 array([-4.2679996,  1.12     ], dtype=float32),
 array([-3.7959197 ,  0.13599992], dtype=float32),
 array([-3.3321245, -0.5192   ], dtype=float32),
 array([-2.9002993 , -0.22375995], dtype=float32),
 array([-2.5103688 ,  0.19247207], dtype=float32),
 array([-2.1647813 ,  0.16962159], dtype=float32),
 array([-1.8621007 , -0.04534957], dtype=float32),
 array([-1.5990343 , -0.09841566], dtype=float32),
 array([-1.371559  , -0.00684991], dtype=float32),
 array([-1.1755278 ,  0.04715286], dtype=float32),
 array([-1.0069805 ,  0.01757081], dtype=float32),
 array([-0.86228806, -0.01830519], dtype=float32),
 array([-0.73820454, -0.01427696], dtype=float32),
 array([-0.6318705,  0.0048695], dtype=float32),
 array([-0.5407913 ,  0.00859933], dtype=float32),
 array([-4.6280417e-01,  1.4504697e-04], dtype=float32),
 array([-0.39604235, -0.00425615], dtype=float32),
 array([-0.3388989 , -0.00134937], dtype=float32)